import { appRoleValues } from "../src/lib/auth/roles";

// Better Auth 1.7.5's CLI cannot express TIMESTAMPTZ or a PostgreSQL role CHECK.
// Preserve its raw output and adjust only these two audited details.
export function normalizeAuthSchema(raw: string): string {
  const userEnd = '  banExpires: timestamp("ban_expires"),\n});';
  if (!raw.includes(userEnd))
    throw new Error(
      "Unexpected Better Auth schema format; review the generator before normalization.",
    );
  const roleLiterals = appRoleValues.map((role) => `'${role}'`).join(", ");
  let code = raw.replace(
    /(import\s*\{)([^}]*)(\}\s*from "drizzle-orm\/pg-core";)/,
    "$1check,$2$3",
  );
  code = code.replace(
    userEnd,
    `  banExpires: timestamp("ban_expires"),\n}, (table) => [check("user_role_valid", sql\`\${table.role} IN (${roleLiterals})\`)]);`,
  );
  code = code.replace(
    /timestamp\("([a-z_]+)"\)/g,
    'timestamp("$1", { withTimezone: true })',
  );
  if (
    code.includes('onDelete: "cascade"') ||
    !code.includes('onDelete: "restrict"')
  ) {
    throw new Error(
      "Generated auth foreign keys do not match the restrictive metadata.",
    );
  }
  return (
    "// Generated by auth@1.7.5; normalized by scripts/auth-schema.mts. Do not hand-edit.\n" +
    code
  );
}
